spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
       implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      
      
    show-sql: true
server:
  port: 8087

